Repository vmware/go-vcloud-director, pull requests merged in 2019-12, with the labels that each got.

#270 Add tests for NSX-V firewall rule with IP sets and VMs
  govcd/api_vcd_test.go
  govcd/entity_test.go
  govcd/nsxv_firewall_test.go
  govcd/system_test.go
  govcd/vm_test.go
Labels: Testing, cla-not-required

#271 Add support for NSX-V Edge Gateway DHCP relay settings
  CHANGELOG.md
  govcd/api_vcd_test.go
  govcd/nsxv_dhcprelay.go
  govcd/nsxv_dhcprelay_test.go
  govcd/nsxv_ipset_test.go
  types/v56/constants.go
  types/v56/nsxv_types.go
Labels: cla-not-required, enhancement

#273 vCD 9.0.0.3 - test error fixes
  govcd/edgegateway.go
  govcd/edgegateway_test.go
  govcd/edgegateway_unit_test.go
  govcd/externalnetwork_test.go
  govcd/system_test.go
  govcd/vm_test.go
  types/v56/constants.go
  types/v56/nsxv_types.go
  types/v56/types.go
Labels: bug, cla-not-required

#275 Do not check for portgroup name when looking up vNic index
  CHANGELOG.md
  govcd/edgegateway.go
  govcd/edgegateway_unit_test.go
Labels: cla-not-required

#274 Allow to pass and override default hard coded api version
  CHANGELOG.md
  govcd/api.go
  govcd/api_test.go
  govcd/api_vcd.go
  govcd/api_vcd_versions.go
  govcd/api_vcd_versions_test.go
  govcd/disk_test.go
  govcd/system_test.go
  govcd/vapp_test.go
  govcd/vm_test.go
  util/logging.go
Labels: cla-not-required
