Repository vmware/go-vcloud-director, pull requests merged in 2020-02, with the labels that each got.

#289 Add handling vApp network functions
  .travis.yml
  CHANGELOG.md
  govcd/system.go
  govcd/system_unit_test.go
  govcd/vapp.go
  govcd/vapp_test.go
  types/v56/types.go
Labels: cla-not-required

#285 VDC supports Flex
  .travis.yml
  CHANGELOG.md
  CODING_GUIDELINES.md
  go.sum
  govcd/adminorg.go
  govcd/adminvdc.go
  govcd/adminvdc_test.go
  govcd/api_vcd_versions.go
  govcd/org.go
  govcd/org_test.go
  govcd/vm_test.go
  types/v56/types.go
Labels: cla-not-required

#288 Fix data race in catalog/media upload reporting
  CHANGELOG.md
  govcd/catalog.go
  govcd/media.go
  govcd/upload.go
  govcd/uploadtask.go
Labels: bug, cla-not-required

#283 Add support for IP reporting when NIC uses DHCP
  .travis.yml
  CHANGELOG.md
  Makefile
  govcd/api_vcd_test.go
  govcd/nsxv_dhcplease.go
  govcd/orgvdcnetwork.go
  govcd/vm.go
  govcd/vm_dhcp_test.go
  govcd/vm_test.go
  types/v56/constants.go
  types/v56/nsxv_types.go
Labels: cla-not-required, enhancement
